export const INTERESTS = {
  anime: [
    { id: "aot", label: "Attack on Titan", emoji: "⚔️" },
    { id: "op", label: "One Piece", emoji: "🏴‍☠️" },
    { id: "jjk", label: "Jujutsu Kaisen", emoji: "🌀" },
    { id: "ds", label: "Demon Slayer", emoji: "🗡️" },
    { id: "csm", label: "Chainsaw Man", emoji: "⛓️" },
    { id: "hxh", label: "Hunter x Hunter", emoji: "🎯" },
    { id: "fma", label: "Fullmetal Alchemist", emoji: "⚗️" },
    { id: "bnha", label: "My Hero Academia", emoji: "💥" },
    { id: "bleach", label: "Bleach", emoji: "☠️" },
    { id: "nrto", label: "Naruto", emoji: "🍥" },
    { id: "vinland", label: "Vinland Saga", emoji: "🪓" },
    { id: "bersk", label: "Berserk", emoji: "🐉" },
  ],
  movies: [
    { id: "marvel", label: "Marvel / MCU", emoji: "🦸" },
    { id: "horror", label: "Horror", emoji: "👻" },
    { id: "scifi", label: "Sci-Fi", emoji: "🚀" },
    { id: "indie", label: "Indie Films", emoji: "🎬" },
    { id: "bollywood", label: "Bollywood", emoji: "🎭" },
    { id: "nolan", label: "Christopher Nolan", emoji: "🌌" },
    { id: "dceu", label: "DC Universe", emoji: "🦇" },
    { id: "anime_films", label: "Anime Films", emoji: "🎌" },
    { id: "thriller", label: "Thriller", emoji: "🔪" },
    { id: "comedy", label: "Comedy", emoji: "😂" },
  ],
  shows: [
    { id: "sitcom", label: "Sitcoms", emoji: "🛋️" },
    { id: "kdrama", label: "K-Drama", emoji: "🇰🇷" },
    { id: "crime", label: "Crime / Mystery", emoji: "🔍" },
    { id: "fantasy", label: "Fantasy", emoji: "🧙" },
    { id: "scifi_tv", label: "Sci-Fi TV", emoji: "🛸" },
    { id: "reality", label: "Reality TV", emoji: "📺" },
    { id: "documentary", label: "Documentaries", emoji: "🎥" },
    { id: "anime_tv", label: "Anime Series", emoji: "📺" },
    { id: "true_crime", label: "True Crime", emoji: "🕵️" },
  ],
  games: [
    { id: "fps", label: "FPS / Shooters", emoji: "🎯" },
    { id: "rpg", label: "RPG", emoji: "⚔️" },
    { id: "moba", label: "MOBA", emoji: "🗺️" },
    { id: "horror_g", label: "Horror Games", emoji: "😱" },
    { id: "indie_g", label: "Indie Games", emoji: "👾" },
    { id: "eldenring", label: "Elden Ring / Souls", emoji: "💀" },
    { id: "valorant", label: "Valorant", emoji: "🔫" },
    { id: "minecraft", label: "Minecraft", emoji: "⛏️" },
    { id: "genshin", label: "Genshin Impact", emoji: "✨" },
    { id: "lol", label: "League of Legends", emoji: "🏆" },
    { id: "strategy", label: "Strategy Games", emoji: "♟️" },
  ],
  memes: [
    { id: "dark", label: "Dark Humor", emoji: "🖤" },
    { id: "genz", label: "Gen Z Memes", emoji: "💀" },
    { id: "dank", label: "Dank Memes", emoji: "🌿" },
    { id: "wholesome", label: "Wholesome", emoji: "🫂" },
    { id: "gaming_m", label: "Gaming Memes", emoji: "🎮" },
    { id: "anime_m", label: "Anime Memes", emoji: "😭" },
    { id: "bollywood_m", label: "Bollywood Memes", emoji: "🕺" },
  ],
};

export const MOCK_GROUPS = [
  {
    id: "g1", name: "Tokyo Ghoul Squad #3", interest: "aot",
    category: "anime", emoji: "⚔️", memberCount: 13, maxMembers: 15,
    location: "Hyderabad Zone", distance: "12 km",
    maleRatio: 0.65, femaleRatio: 0.35,
    challenge: "Rewatch the final season and share your hot takes!",
    description: "Die-hard AoT fans discussing lore, theories, and the controversial ending.",
    topicOfWeek: "Was Eren right? The ethics of the Rumbling.",
    online: 7, active: true,
    members: [
      { id: "u1", name: "Arjun K", gender: "m", city: "Hyderabad", vibe: 94, initials: "AK" },
      { id: "u2", name: "Priya S", gender: "f", city: "Hyderabad", vibe: 87, initials: "PS" },
      { id: "u3", name: "Ravi M", gender: "m", city: "Secunderabad", vibe: 82, initials: "RM" },
      { id: "u4", name: "Ananya T", gender: "f", city: "Hyderabad", vibe: 78, initials: "AT" },
      { id: "u5", name: "Kiran B", gender: "m", city: "Pune", vibe: 91, initials: "KB" },
    ],
    messages: [
      { id: "m1", user: "Arjun K", uid: "u1", initials: "AK", text: "The founding titan reveal was insane 🤯", time: "2:30 PM", reactions: { "🔥": 4, "😭": 2 } },
      { id: "m2", user: "Priya S", uid: "u2", initials: "PS", text: "I still can't believe what they did with Hange though", time: "2:32 PM", reactions: { "💔": 5 } },
      { id: "m3", user: "Ravi M", uid: "u3", initials: "RM", text: "HOT TAKE: The manga ending was actually perfect", time: "2:35 PM", reactions: { "🤔": 3, "💀": 2 } },
      { id: "m4", user: "Ananya T", uid: "u4", initials: "AT", text: "Ravi you absolute menace 😭😭", time: "2:36 PM", reactions: { "😂": 6 } },
    ],
    memes: ["😭", "🔥", "💀", "🤯", "😂", "⚔️"],
    polls: [{ q: "Best arc in AoT?", opts: [{ t: "Marley Arc", v: 5 }, { t: "Final Season", v: 3 }, { t: "Clash of Titans", v: 2 }, { t: "Return to Shiganshina", v: 4 }] }],
    events: [{ id: "e1", title: "AoT Final Season Rewatch Party", day: "28", month: "Apr", rsvp: 9 }],
    badges: ["S-Rank Otaku", "Theory Crafter", "Lore Master"],
  },
  {
    id: "g2", name: "Pirate King Believers #7", interest: "op",
    category: "anime", emoji: "🏴‍☠️", memberCount: 15, maxMembers: 15,
    location: "Vijayawada Zone", distance: "2 km",
    maleRatio: 0.6, femaleRatio: 0.4,
    challenge: "Share your top 3 One Piece arcs and defend your choices!",
    description: "One Piece fans only. No spoilers without tags. Gear 5 believers welcome.",
    topicOfWeek: "Gear 5 Luffy vs all previous final bosses — who wins?",
    online: 11, active: true,
    members: [
      { id: "u6", name: "Rohan P", gender: "m", city: "Vijayawada", vibe: 96, initials: "RP" },
      { id: "u7", name: "Divya N", gender: "f", city: "Vijayawada", vibe: 88, initials: "DN" },
      { id: "u8", name: "Sai K", gender: "m", city: "Guntur", vibe: 85, initials: "SK" },
    ],
    messages: [
      { id: "m5", user: "Rohan P", uid: "u6", initials: "RP", text: "Oda really said 'let me break your heart AND heal it in the same chapter'", time: "1:15 PM", reactions: { "😭": 8, "🔥": 3 } },
      { id: "m6", user: "Divya N", uid: "u7", initials: "DN", text: "Gear 5 was the greatest anime moment of the decade fight me", time: "1:18 PM", reactions: { "🔥": 11 } },
    ],
    memes: ["🏴‍☠️", "😭", "🔥", "⚓", "🌊", "✨"],
    polls: [{ q: "Best One Piece arc?", opts: [{ t: "Marineford", v: 8 }, { t: "Wano", v: 6 }, { t: "Enies Lobby", v: 5 }, { t: "Dressrosa", v: 2 }] }],
    events: [{ id: "e2", title: "Live React: Latest One Piece Chapter", day: "30", month: "Apr", rsvp: 13 }],
    badges: ["Yonko Level", "Nakama Forever"],
  },
  {
    id: "g3", name: "Cursed Energy Enthusiasts #2", interest: "jjk",
    category: "anime", emoji: "🌀", memberCount: 11, maxMembers: 15,
    location: "Vijayawada Zone", distance: "5 km",
    maleRatio: 0.55, femaleRatio: 0.45,
    challenge: "Who is the better character: Gojo or Sukuna? State your case.",
    description: "JJK stans who live and breathe cursed energy. Manga readers, anime-only, all welcome.",
    topicOfWeek: "Post-Gojo JJK — is the manga still worth reading?",
    online: 5, active: true,
    members: [
      { id: "u9", name: "Meera R", gender: "f", city: "Vijayawada", vibe: 93, initials: "MR" },
      { id: "u10", name: "Aryan D", gender: "m", city: "Vijayawada", vibe: 89, initials: "AD" },
    ],
    messages: [
      { id: "m7", user: "Meera R", uid: "u9", initials: "MR", text: "THAT CHAPTER. I can't. I'm going to cry.", time: "11:00 AM", isSpoiler: true, reactions: { "😭": 9 } },
      { id: "m8", user: "Aryan D", uid: "u10", initials: "AD", text: "Gege Akutami is a menace to society and I love him for it", time: "11:03 AM", reactions: { "😂": 4, "💀": 6 } },
    ],
    memes: ["🌀", "💀", "😭", "✨", "🔥", "🫠"],
    polls: [{ q: "Gojo vs Sukuna?", opts: [{ t: "Gojo Satoru", v: 7 }, { t: "Ryomen Sukuna", v: 5 }, { t: "Both are GOAT", v: 3 }] }],
    events: [{ id: "e3", title: "JJK Season 2 Full Rewatch", day: "5", month: "May", rsvp: 8 }],
    badges: ["Cursed Technique Master"],
  },
  {
    id: "g4", name: "The Valorant Agents #12", interest: "valorant",
    category: "games", emoji: "🔫", memberCount: 14, maxMembers: 15,
    location: "Hyderabad Zone", distance: "18 km",
    maleRatio: 0.75, femaleRatio: 0.25,
    challenge: "5-stack ranked session this weekend! Iron to Radiant welcome.",
    description: "Valorant players — rank up, discuss meta, find your squad.",
    topicOfWeek: "Best agent composition for current meta?",
    online: 9, active: true,
    members: [
      { id: "u11", name: "Nikhil G", gender: "m", city: "Hyderabad", vibe: 80, initials: "NG" },
      { id: "u12", name: "Sneha T", gender: "f", city: "Hyderabad", vibe: 88, initials: "ST" },
    ],
    messages: [
      { id: "m9", user: "Nikhil G", uid: "u11", initials: "NG", text: "Who's down for ranked grind tonight? Need 2 more", time: "4:00 PM", reactions: { "🙋": 5 } },
      { id: "m10", user: "Sneha T", uid: "u12", initials: "ST", text: "I'm in! Finally hit Diamond last night 🔥", time: "4:02 PM", reactions: { "🔥": 7, "🎉": 4 } },
    ],
    memes: ["🔫", "🎯", "💀", "😤", "🏆", "😎"],
    polls: [{ q: "Best agent in current meta?", opts: [{ t: "Jett", v: 4 }, { t: "Clove", v: 6 }, { t: "Cypher", v: 3 }, { t: "Deadlock", v: 2 }] }],
    events: [{ id: "e4", title: "5-Stack Ranked Session", day: "27", month: "Apr", rsvp: 10 }],
    badges: ["Radiant Hunter", "Clutch King"],
  },
  {
    id: "g5", name: "Horror Heads #4", interest: "horror",
    category: "movies", emoji: "👻", memberCount: 12, maxMembers: 15,
    location: "Chennai Zone", distance: "340 km",
    maleRatio: 0.5, femaleRatio: 0.5,
    challenge: "Rate every A24 horror film — share your tier list!",
    description: "Horror movie lovers who appreciate slow-burn dread and jump scare haters.",
    topicOfWeek: "Best horror film of 2024 — make your case.",
    online: 3, active: false,
    members: [],
    messages: [
      { id: "m11", user: "Aisha M", uid: "u13", initials: "AM", text: "Hereditary still lives rent free in my head and it's been 3 years", time: "Yesterday", reactions: { "😱": 8 } },
    ],
    memes: ["👻", "😱", "🩸", "🔪", "😈", "💀"],
    polls: [{ q: "Best A24 horror?", opts: [{ t: "Hereditary", v: 6 }, { t: "Midsommar", v: 4 }, { t: "The VVitch", v: 3 }, { t: "Talk to Me", v: 5 }] }],
    events: [],
    badges: ["Final Girl", "Jump Scare Immune"],
  },
  {
    id: "g6", name: "Elden Ring Tarnished #6", interest: "eldenring",
    category: "games", emoji: "💀", memberCount: 13, maxMembers: 15,
    location: "Bengaluru Zone", distance: "280 km",
    maleRatio: 0.72, femaleRatio: 0.28,
    challenge: "No summons, no ashes — challenge run this week!",
    description: "Touch grace. Git gud. Share your builds and boss kill screenshots.",
    topicOfWeek: "Shadow of the Erdtree — is Messmer the best boss From has ever made?",
    online: 6, active: true,
    members: [],
    messages: [
      { id: "m12", user: "Vikram S", uid: "u14", initials: "VS", text: "Malenia finally down after 87 attempts. Worth it. 🗡️", time: "3:00 PM", reactions: { "🏆": 12, "🔥": 9 } },
    ],
    memes: ["💀", "⚔️", "🐉", "😤", "🏆", "🫀"],
    polls: [{ q: "Hardest Elden Ring boss?", opts: [{ t: "Malenia", v: 9 }, { t: "Maliketh", v: 4 }, { t: "Radahn", v: 5 }, { t: "Morgott", v: 2 }] }],
    events: [{ id: "e5", title: "Shadow of the Erdtree Speedrun Watch", day: "3", month: "May", rsvp: 7 }],
    badges: ["Elden Lord", "Malenia Slayer"],
  },
];

export const CONTENT_LIBRARY = {
  anime: [
    { id: "a1", title: "Attack on Titan", genre: "Action/Dark Fantasy", episodes: 87, status: "Completed", rating: 9.0, year: 2013, img: "⚔️" },
    { id: "a2", title: "One Piece", genre: "Adventure/Shounen", episodes: "1100+", status: "Ongoing", rating: 8.9, year: 1999, img: "🏴‍☠️" },
    { id: "a3", title: "Jujutsu Kaisen", genre: "Action/Supernatural", episodes: 47, status: "Ongoing", rating: 8.7, year: 2020, img: "🌀" },
    { id: "a4", title: "Demon Slayer", genre: "Action/Historical", episodes: 55, status: "Ongoing", rating: 8.6, year: 2019, img: "🗡️" },
    { id: "a5", title: "Chainsaw Man", genre: "Action/Horror", episodes: 12, status: "Ongoing", rating: 8.5, year: 2022, img: "⛓️" },
    { id: "a6", title: "Hunter x Hunter", genre: "Adventure/Shounen", episodes: 148, status: "Hiatus", rating: 9.1, year: 2011, img: "🎯" },
    { id: "a7", title: "Fullmetal Alchemist: Brotherhood", genre: "Action/Fantasy", episodes: 64, status: "Completed", rating: 9.1, year: 2009, img: "⚗️" },
    { id: "a8", title: "Vinland Saga", genre: "Historical/Action", episodes: 48, status: "Ongoing", rating: 8.8, year: 2019, img: "🪓" },
  ],
  movies: [
    { id: "mv1", title: "Avengers: Endgame", genre: "Superhero/Action", year: 2019, rating: 8.4, director: "Russo Brothers", img: "🦸" },
    { id: "mv2", title: "Hereditary", genre: "Horror", year: 2018, rating: 7.3, director: "Ari Aster", img: "👻" },
    { id: "mv3", title: "Oppenheimer", genre: "Biographical/Thriller", year: 2023, rating: 8.3, director: "Christopher Nolan", img: "💥" },
    { id: "mv4", title: "Everything Everywhere All at Once", genre: "Sci-Fi/Comedy", year: 2022, rating: 7.8, director: "The Daniels", img: "🌌" },
    { id: "mv5", title: "Interstellar", genre: "Sci-Fi", year: 2014, rating: 8.7, director: "Christopher Nolan", img: "🚀" },
    { id: "mv6", title: "The Dark Knight", genre: "Superhero/Thriller", year: 2008, rating: 9.0, director: "Christopher Nolan", img: "🦇" },
  ],
  games: [
    { id: "gm1", title: "Elden Ring", genre: "Action RPG", platform: "Multi", metacritic: 96, year: 2022, img: "💀", developer: "FromSoftware" },
    { id: "gm2", title: "Valorant", genre: "Tactical FPS", platform: "PC", metacritic: 80, year: 2020, img: "🔫", developer: "Riot Games" },
    { id: "gm3", title: "Minecraft", genre: "Sandbox", platform: "Multi", metacritic: 93, year: 2011, img: "⛏️", developer: "Mojang" },
    { id: "gm4", title: "Genshin Impact", genre: "Action RPG", platform: "Multi", metacritic: 84, year: 2020, img: "✨", developer: "HoYoverse" },
    { id: "gm5", title: "League of Legends", genre: "MOBA", platform: "PC", metacritic: 78, year: 2009, img: "🏆", developer: "Riot Games" },
    { id: "gm6", title: "Hollow Knight", genre: "Indie/Metroidvania", platform: "Multi", metacritic: 87, year: 2017, img: "🦋", developer: "Team Cherry" },
  ],
  shows: [
    { id: "sh1", title: "Breaking Bad", genre: "Crime/Drama", seasons: 5, status: "Completed", rating: 9.5, year: 2008, img: "⚗️" },
    { id: "sh2", title: "Squid Game", genre: "Thriller/K-Drama", seasons: 2, status: "Ongoing", rating: 8.0, year: 2021, img: "🎭" },
    { id: "sh3", title: "The Last of Us", genre: "Drama/Sci-Fi", seasons: 2, status: "Ongoing", rating: 8.8, year: 2023, img: "🍄" },
    { id: "sh4", title: "Stranger Things", genre: "Sci-Fi/Horror", seasons: 4, status: "Completed", rating: 8.7, year: 2016, img: "🔦" },
    { id: "sh5", title: "The Office", genre: "Sitcom/Comedy", seasons: 9, status: "Completed", rating: 9.0, year: 2005, img: "📋" },
    { id: "sh6", title: "House of the Dragon", genre: "Fantasy/Drama", seasons: 2, status: "Ongoing", rating: 8.4, year: 2022, img: "🐉" },
  ],
};

export const ICE_BREAKERS = [
  "Welcome! Quick: pick one — Anime Movie Night or Game Night?",
  "Introduce yourself! What's the one show/game that defines your personality?",
  "Hot take time! Share yours — no wrong answers here.",
  "Which character from your fandom would you actually be friends with IRL?",
  "Rate the current topic on a scale of 1-10. Justify your answer!",
];

export const BADGES_LIST = [
  { id: "b1", name: "S-Rank Otaku", icon: "⭐", desc: "Top anime enthusiast in your group" },
  { id: "b2", name: "Nakama Forever", icon: "🤝", desc: "Active in a group for 30+ days" },
  { id: "b3", name: "Theory Crafter", icon: "🧠", desc: "Submitted 10+ discussion topics" },
  { id: "b4", name: "Meme Lord", icon: "😂", desc: "Posted 50+ memes in the Meme Board" },
  { id: "b5", name: "Event Host", icon: "🎉", desc: "Organized 3+ group events" },
  { id: "b6", name: "Clutch King", icon: "🏆", desc: "Won the weekly group challenge" },
  { id: "b7", name: "Spoiler Guard", icon: "🛡️", desc: "Always tags spoilers properly" },
  { id: "b8", name: "Newcomer", icon: "🌟", desc: "Just joined the platform!" },
];
